apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
  namespace: hireverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: hireverse/user-server
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DATABASE_URL
            - name: MSAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MSAL_CLIENT_ID
            - name: MSAL_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MSAL_TENANT_ID
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET_KEY
          envFrom:
            - configMapRef:
                name: common-config

---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
  namespace: hireverse
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 5001
      targetPort: 5001
